name: Credit Scoring Automated Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ml_pipeline_execution:
    name: Build Environment and Run MLflow Project
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.12.7']

    steps:
    - name: Fetch Source Code From GitHub
      uses: actions/checkout@v3

    - name: Initialize Python Runtime Environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install Core Application Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute MLflow Project Tracking Pipeline
      env:
        MLFLOW_ALLOW_FILE_STORE: "true"
        MLFLOW_TRACKING_USERNAME: "meiras28"
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        mlflow run . --entry-point main --run-name "CI_Run_${{ github.run_number }}"
